import Link from "next/link";
import { Clock3, MapPin } from "lucide-react";
import type { Assignment } from "@/types/assignment";

export default function TodayDuties({ assignments }: { assignments: Assignment[] }) {
  const today = new Date().toISOString().slice(0, 10);
  const duties = assignments.filter((item) => item.dutyDate.slice(0, 10) === today).slice(0, 4);
  return <section className="rounded-2xl border border-[#e8e1d8] bg-white p-5 shadow-sm"><div className="flex items-center justify-between pb-4"><div><h2 className="text-base font-bold text-[#29241f]">Today&apos;s Assigned Duties</h2><p className="text-xs text-[#756d64]">Live duties assigned to your shift</p></div><Link href="/staff/duties" className="text-xs font-semibold text-[#9a6c37] hover:underline">View All</Link></div>{duties.length === 0 ? <p className="rounded-xl bg-[#fdfcfb] p-4 text-sm text-gray-500">No duties assigned for today.</p> : <div className="space-y-3">{duties.map((duty) => { const event = typeof duty.event === "string" ? null : duty.event; return <div key={duty._id} className="flex flex-col gap-3 rounded-xl border border-gray-100 bg-[#fdfcfb] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="space-y-1"><div className="flex items-center gap-2"><span className="font-semibold text-[#29241f]">{duty.dutyTitle}</span><span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold text-amber-700">{duty.status}</span></div><p className="text-xs text-gray-500">{event?.eventName || "Assigned event"}</p><div className="flex flex-wrap items-center gap-3 pt-1 text-[11px] text-gray-400"><span className="flex items-center gap-1"><Clock3 size={12} />{duty.startTime} - {duty.endTime}</span><span className="flex items-center gap-1"><MapPin size={12} />{event?.location || "Location pending"}</span></div></div></div>; })}</div>}</section>;
}
