import type { EventCardData } from "./EventCard";

export const events: EventCardData[] = [
  {
    id: 1,
    title: "Wedding Celebration",
    type: "Wedding",
    date: "Sep 12, 2026",
    time: "6:00 PM",
    location: "Grand Palace, Kochi",
    guests: 250,
    customer: "Anjali Menon",
    package: "Premium",
    amount: "₹85,000",
    status: "Confirmed",
  },
  {
    id: 2,
    title: "Birthday Celebration",
    type: "Birthday",
    date: "Sep 15, 2026",
    time: "7:00 PM",
    location: "Royal Banquet Hall",
    guests: 80,
    customer: "Rahul Kumar",
    package: "Starter",
    amount: "₹25,000",
    status: "Pending",
  },
  {
    id: 3,
    title: "Corporate Conference",
    type: "Corporate Event",
    date: "Sep 18, 2026",
    time: "10:00 AM",
    location: "Business Centre, Kochi",
    guests: 120,
    customer: "Arjun Thomas",
    package: "Medium",
    amount: "₹50,000",
    status: "Pending",
  },
  {
    id: 4,
    title: "Engagement Ceremony",
    type: "Engagement",
    date: "Sep 21, 2026",
    time: "5:30 PM",
    location: "Lake View Convention Centre",
    guests: 150,
    customer: "Meera Nair",
    package: "Medium",
    amount: "₹50,000",
    status: "Confirmed",
  },
];